plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.btvn'
version = '0.0.1-SNAPSHOT'
description = 'ServiceProjectFinal'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Core
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // Cloudinary
    implementation 'com.cloudinary:cloudinary-http45:1.39.0'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // BCrypt
    implementation 'org.mindrot:jbcrypt:0.4'

    // DB
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // TEST
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}


//plugins {
//    id 'java'
//    id 'org.springframework.boot' version '4.0.6'
//    id 'io.spring.dependency-management' version '1.1.7'
//}
//
//group = 'com.btvn'
//version = '0.0.1-SNAPSHOT'
//description = 'ServiceProjectFinal'
//
//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(17)
//    }
//}
//
//repositories {
//    mavenCentral()
//}
//
//
//dependencies {
//    runtimeOnly 'com.h2database:h2'
//    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
//    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
//    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
//    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
//    testImplementation 'org.mockito:mockito-core'
//
//    // Core
//    implementation 'org.springframework.boot:spring-boot-starter-web'
//    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
//    implementation 'org.springframework.boot:spring-boot-starter-security'
//    implementation 'org.springframework.boot:spring-boot-starter-validation'
//    implementation 'org.springframework.boot:spring-boot-starter-aop'
//
//    // Mail
//    implementation 'org.springframework.boot:spring-boot-starter-mail'
//
//    // Cloudinary
//    implementation 'com.cloudinary:cloudinary-http45:1.39.0'
//
//    // JWT
//    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
//    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
//    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
//
//    // BCrypt
//    implementation 'org.mindrot:jbcrypt:0.4'
//
//    // DB
//    runtimeOnly 'com.mysql:mysql-connector-j'
//
//    // Lombok
//    compileOnly 'org.projectlombok:lombok'
//    annotationProcessor 'org.projectlombok:lombok'
//
//    // DevTools
//    developmentOnly 'org.springframework.boot:spring-boot-devtools'
//
//    // TEST
//    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//    testImplementation 'org.springframework.security:spring-security-test'
//    testRuntimeOnly 'com.h2database:h2'
//    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
//    testCompileOnly 'org.projectlombok:lombok'
//    testAnnotationProcessor 'org.projectlombok:lombok'
//
//    // build.gradle
//    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
//}
//
//tasks.named('test') {
//    useJUnitPlatform()
//}
