spring.application.name=ServiceProjectFinal

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/job_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-256-bit-base64-encoded-secret-key-here-must-be-long-enough
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000

# CLOUDINARY
cloudinary.cloud-name=dttookk0w
cloudinary.api-key=881535761498262
cloudinary.api-secret=I8W3M-2yyQ_gpSF2I9PFyu1xT0k

# EMAIL (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=haminhtrang545@gmail.com
spring.mail.password=mziy ndai lfdy jidd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP
otp.expiration-minutes=5